### ISSUE TITLE
got an error

### ISSUE THREAD

**Issue by Rolandisimo1** [movestore/dynBrownianBridge#4]
Error in validityMethod(as(object, superClass)): Length does not match between means, in.windows and interest (407, 407, 438)

**Comment by annescharf** [comment]
Hi @Rolandisimo1, I realized yesterday that I did not deprecate the old move1 version of this App. Could you let me know if the error occurred in the App "Utilisation Distribution (Dynamic Brownian Bridge) (move)" or in the updated one "Occurrence Distribution (Dynamic Brownian Bridge)". Thanks!
